
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class shift_close extends javax.swing.JFrame {

    /**
     * Creates new form shift_close
     */
    Connection conn=null;
    Statement st=null;
    ResultSet rs=null;
    int safe=1;
    String qry1=null;
    String pump_type;
    int  ending_id;
    public shift_close() {
         conn=DBconnect.connect();
        initComponents();
        this.additem();
        jPanel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("PUMP NAME :");

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Pumps....." }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Current Reading", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(0, 0, 51))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("PETROL VOLUME  :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("DIESEL VOLUME  :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("OIL VOLUME  :");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        jFormattedTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        jFormattedTextField2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        jFormattedTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(jFormattedTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                        .addGap(185, 185, 185))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 204));
        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(346, 346, 346))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        if(safe==2 && jComboBox1.getSelectedIndex()==0){
            jLabel2.setText("");
            jPanel2.setVisible(false);
            jFormattedTextField1.setVisible(false);
            jFormattedTextField2.setVisible(false);
            jFormattedTextField3.setVisible(false);
            
            qry1=null;
        }
        else if( (safe==2) && (jComboBox1.getSelectedIndex()!=0) )
        {
            String qry="SELECT tank_type from tank where tank_name='"+(jComboBox1.getSelectedItem())+"'";
            try {
                st=conn.createStatement();
                rs=st.executeQuery(qry);
                while (rs.next())
                {
                  
                  pump_type=""+(rs.getString("tank_type"));
                  jLabel2.setText(pump_type);
                  this.give_data();
                }
            } catch (SQLException ex) {
                Logger.getLogger(shift_close.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String qry=null,qry1=null,qry2=null,qry3=null,qry4=null,qry6=null;
        String qry5="select ending_sales_id from shift  order by ending_sales_id desc limit 1 ";
        try {
              st=conn.createStatement();
              rs=st.executeQuery(qry5);
              
              if(!rs.next()){
                   ending_id=0;
                   System.out.println("No data");
              }else 
              {
                ending_id=rs.getInt("ending_sales_id");
                  
              }
        } catch (SQLException ex) {
            Logger.getLogger(shift_close.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(pump_type.equals("PETROL"))
        { 
          qry="UPDATE reading_petrol set current_reading='"+(jFormattedTextField1.getValue())+"'where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
       qry1="UPDATE petrol_updation set current_reading='"+(jFormattedTextField1.getValue())+"'where tank_name='"+(jComboBox1.getSelectedItem())+"'";            
          
        }
        if(pump_type.equals("DIESEL"))
        {
            qry="UPDATE reading_diesel set current_reading='"+(jFormattedTextField2.getValue())+"'where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
           qry1="UPDATE diesel_updation set current_reading='"+(jFormattedTextField2.getValue())+"'where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
            
            
        }
        if(pump_type.equals("OIL"))
        {
            qry="UPDATE reading_oil set current_reading='"+(jFormattedTextField3.getValue())+"'where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
            qry1="UPDATE oil_updation set current_reading='"+(jFormattedTextField3.getValue())+"'where tank_name='"+(jComboBox1.getSelectedItem())+"'";  
        }
        if(pump_type.equals("PETROL AND DIESEL"))
        {
            
            qry="UPDATE reading_petrol set current_reading='"+(jFormattedTextField1.getValue())+"'  where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
            qry1="UPDATE reading_diesel set current_reading='"+(jFormattedTextField2.getValue())+"'  where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
             qry2="UPDATE petrol_updation set current_reading='"+(jFormattedTextField1.getValue())+"'  where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
            qry3="UPDATE diesel_updation set current_reading='"+(jFormattedTextField2.getValue())+"'  where tank_name='"+(jComboBox1.getSelectedItem())+"'";         
        }
        if(pump_type.equals("PETROL AND OIL"))
        {
            
            qry="UPDATE reading_petrol set current_reading='"+(jFormattedTextField1.getValue())+"' where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
            qry1="UPDATE reading_oil set current_reading='"+(jFormattedTextField3.getValue())+"'  where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
       qry2="UPDATE petrol_updation set current_reading='"+(jFormattedTextField1.getValue())+"' where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
            qry3="UPDATE oil_updation set current_reading='"+(jFormattedTextField3.getValue())+"'  where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
        }
        if(pump_type.equals("DIESEL AND OIL"))
        {
           
            
            qry="UPDATE reading_diesel set current_reading='"+(jFormattedTextField2.getValue())+"'  where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
            qry1="UPDATE reading_oil set current_reading='"+(jFormattedTextField3.getValue())+"'  where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
        qry2="UPDATE diesel_updation set current_reading='"+(jFormattedTextField2.getValue())+"' where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
            qry3="UPDATE oil_updation set current_reading='"+(jFormattedTextField3.getValue())+"'  where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
        }
        if(pump_type.equals("PETROL AND DIESEL AND OIL"))
        {
           
            qry="UPDATE reading_petrol set current_reading='"+(jFormattedTextField1.getValue())+"'  where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
            qry1="UPDATE reading_diesel set current_reading='"+(jFormattedTextField2.getValue())+"'  where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
            qry2="UPDATE reading_oil set current_reading='"+(jFormattedTextField3.getValue())+"'  where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
            qry3="UPDATE petrol_updation set current_reading='"+(jFormattedTextField1.getValue())+"'  where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
            qry4="UPDATE diesel_updation set current_reading='"+(jFormattedTextField2.getValue())+"'  where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
            qry6="UPDATE oil_updation set current_reading='"+(jFormattedTextField3.getValue())+"'  where tank_name='"+(jComboBox1.getSelectedItem())+"'"; 
        }
        PreparedStatement pst;
            try {
                pst = conn.prepareStatement(qry);
                 pst.executeUpdate();
                  pst = conn.prepareStatement(qry1);
                 pst.executeUpdate();
                  pst = conn.prepareStatement(qry2);
                 pst.executeUpdate();
                  pst = conn.prepareStatement(qry3);
                 pst.executeUpdate();
                  pst = conn.prepareStatement(qry4);
                 pst.executeUpdate();
                  pst = conn.prepareStatement(qry6);
                 pst.executeUpdate();
                 
            } catch (SQLException ex) {
                Logger.getLogger(tankcreation.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null,"Updated Successfully");
            this.setVisible(true);
              
          jFormattedTextField1.setText("");
            jFormattedTextField2.setText("");
            jFormattedTextField3.setText("");
            jLabel2.setText("");
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        new home().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         new vimal_update().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void give_data()
    {
        if(pump_type.equals("PETROL"))
        {
            jPanel2.setVisible(true);
            jLabel3.setVisible(true);
                  jLabel4.setVisible(false);
                   jLabel5.setVisible(false);
                   jButton1.setVisible(true);
             jFormattedTextField1.setVisible(true);
            jFormattedTextField2.setVisible(false);
            jFormattedTextField3.setVisible(false);
             jFormattedTextField1.setEditable(true);
            jFormattedTextField2.setEditable(false);
            jFormattedTextField3.setEditable(false);
        }
        if(pump_type.equals("DIESEL"))
        { jPanel2.setVisible(true);
            jLabel3.setVisible(false);
                  jLabel4.setVisible(true);
                   jLabel5.setVisible(false);
                   jButton1.setVisible(true);
             jFormattedTextField1.setVisible(false);
            jFormattedTextField2.setVisible(true);
            jFormattedTextField3.setVisible(false);
             jFormattedTextField1.setEditable(false);
            jFormattedTextField2.setEditable(true);
            jFormattedTextField3.setEditable(false);
        }
        if(pump_type.equals("OIL"))
        {
             jPanel2.setVisible(true);
            jLabel3.setVisible(false);
                  jLabel4.setVisible(false);
                   jLabel5.setVisible(true);
                   jButton1.setVisible(true);
             jFormattedTextField1.setVisible(false);
            jFormattedTextField2.setVisible(false);
            jFormattedTextField3.setVisible(true);
             jFormattedTextField1.setEditable(false);
            jFormattedTextField2.setEditable(false);
            jFormattedTextField3.setEditable(true);
        }
        if(pump_type.equals("PETROL AND DIESEL"))
        {
             jPanel2.setVisible(true);
            jLabel3.setVisible(true);
                  jLabel4.setVisible(true);
                   jLabel5.setVisible(false);
                   jButton1.setVisible(true);
             jFormattedTextField1.setVisible(true);
            jFormattedTextField2.setVisible(true);
            jFormattedTextField3.setVisible(false);
             jFormattedTextField1.setEditable(true);
            jFormattedTextField2.setEditable(true);
            jFormattedTextField3.setEditable(false);
        }
        if(pump_type.equals("PETROL AND OIL"))
        {
             jPanel2.setVisible(true);
            jLabel3.setVisible(true);
                  jLabel4.setVisible(false);
                   jLabel5.setVisible(true);
                   jButton1.setVisible(true);
             jFormattedTextField1.setVisible(true);
            jFormattedTextField2.setVisible(false);
            jFormattedTextField3.setVisible(true);
             jFormattedTextField1.setEditable(true);
            jFormattedTextField2.setEditable(false);
            jFormattedTextField3.setEditable(true);
        }
        if(pump_type.equals("DIESEL AND OIL"))
        {
             jPanel2.setVisible(true);
            jLabel3.setVisible(false);
                  jLabel4.setVisible(true);
                   jLabel5.setVisible(true);
                   jButton1.setVisible(true);
             jFormattedTextField1.setVisible(false);
            jFormattedTextField2.setVisible(true);
            jFormattedTextField3.setVisible(true);
             jFormattedTextField1.setEditable(false);
            jFormattedTextField2.setEditable(true);
            jFormattedTextField3.setEditable(true);
        }
        if(pump_type.equals("PETROL AND DIESEL AND OIL"))
        {
             jPanel2.setVisible(true);
            jLabel3.setVisible(true);
                  jLabel4.setVisible(true);
                   jLabel5.setVisible(true);
                   jButton1.setVisible(true);
             jFormattedTextField1.setVisible(true);
            jFormattedTextField2.setVisible(true);
            jFormattedTextField3.setVisible(true);
             jFormattedTextField1.setEditable(true);
            jFormattedTextField2.setEditable(true);
            jFormattedTextField3.setEditable(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public void additem() 
    {
        String qry="select * from tank";
        try {
            st=conn.createStatement();
              rs=st.executeQuery(qry);
               while(rs.next()){
             
              jComboBox1.addItem(""+(rs.getString("tank_name")));
              
               }
               safe=2;
               } catch (SQLException ex) {
            Logger.getLogger(shift_close.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shift_close.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shift_close.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shift_close.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shift_close.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              new shift_close().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
